version: '3'

services:
  info-app:
    build: .
    ports:
      - 80:3838
    networks:
      - net
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - net

networks:
  net:
