version: '3'

services:
  app:
    build:
      context: ./app
    container_name: app
    ports:
      - 80:3838
    volumes:
      - ./app:/srv/shiny-server/
      - packages:/usr/local/lib/R/site-library
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
  spacy:
    build:
      context: ./conda
    container_name: spacy
    ports:
      - 8888:8888
    volumes:
      - conda:/opt/conda
  rstudio:
    image: rocker/rstudio
    container_name: rstudio
    environment:
      - PASSWORD=test
#      - ADD=shiny
    ports:
      - 8787:8787
    volumes:
      - .:/home/rstudio/info-app
      - packages:/usr/local/lib/R/site-library
      - conda:/home/rstudio/miniconda
    depends_on:
      - app

volumes:
  packages:
  conda:
