version: '3'

services:
  app:
    image: vallivh/info-app
    container_name: app
    ports:
      - 80:3838
    depends_on:
      - mongodb
      # - spacy
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
  # spacy:
  #   build:
  #     context: ./conda
  #   container_name: spacy
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - ./conda/opt:/opt/conda
